services:
    eigen-api-db:
        image: postgres
        container_name: eigen-api-db
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - app-volume:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - eigen-network
    eigen-api:
        container_name: eigen-central-api
        ports:
        - "13000:3000"
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            eigen-api-db:
                condition: service_healthy
        env_file:
            - .env
        restart: always
        networks:
            - eigen-network


volumes:
  app-volume:

networks:
  eigen-network:
    driver: bridge
    